apiVersion: v1
kind: Secret
metadata:
  name: malulos-secrets
  namespace: malulos-ns
type: Opaque
stringData:
  POSTGRES_DB: "malulos_pos"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "CHANGE_ME_PLEASE"
  TELEGRAM_BOT_TOKEN: "CHANGE_ME_PLEASE"
