apiVersion: apps/v1
kind: Deployment
metadata:
  name: malulos-api
  namespace: malulos-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: malulos-api
  template:
    metadata:
      labels:
        app: malulos-api
    spec:
      containers:
      - name: malulos-api
        image: tu-usuario-dockerhub/malulos-api:latest # REEMPLAZAR con tu imagen real
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db:5432/$(POSTGRES_DB)"
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: malulos-secrets
              key: TELEGRAM_BOT_TOKEN
        envFrom:
        - secretRef:
            name: malulos-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: malulos-ns
spec:
  selector:
    app: malulos-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
